/*
============================================================
FILE NAME   : magnitude_exploration.sql
PROJECT     : Exploratory Data Analysis
PURPOSE     :
- To analyze the magnitude and distribution of customers, products, and revenue
- To understand business scale across countries, categories, and customers
- To support Exploratory Data Analysis (EDA) for business insights
- To identify high-performing regions, categories, and customers
============================================================
*/

------------------------------------------------------------
-- MAGNITUDE EXPLORATION
------------------------------------------------------------

------------------------------------------------------------
-- 1. TOTAL CUSTOMERS BY COUNTRY
------------------------------------------------------------
-- Business Question:
-- Which countries have the highest number of customers?
SELECT 
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


------------------------------------------------------------
-- 2. TOTAL CUSTOMERS BY GENDER
------------------------------------------------------------
-- Business Question:
-- What is the customer distribution by gender?
SELECT 
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


------------------------------------------------------------
-- 3. TOTAL PRODUCTS BY COUNTRY
------------------------------------------------------------
-- Business Question:
-- How are products distributed across customer countries?
SELECT 
    c.country,
    COUNT(p.product_name) AS total_products
FROM gold.dim_products p
LEFT JOIN gold.dim_customers c
    ON c.customer_key = p.product_key
GROUP BY c.country
ORDER BY total_products DESC;


------------------------------------------------------------
-- 4. TOTAL PRODUCTS BY CATEGORY
------------------------------------------------------------
-- Business Question:
-- Which product categories have the most products?
SELECT 
    category,
    COUNT(product_name) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


------------------------------------------------------------
-- 5. AVERAGE COST BY PRODUCT CATEGORY
------------------------------------------------------------
-- Business Question:
-- What is the average product cost in each category?
SELECT 
    category,
    AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;


------------------------------------------------------------
-- 6. TOTAL REVENUE BY PRODUCT CATEGORY
------------------------------------------------------------
-- Business Question:
-- Which product categories generate the most revenue?
SELECT 
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


------------------------------------------------------------
-- 7. TOTAL REVENUE GENERATED BY EACH CUSTOMER
------------------------------------------------------------
-- Business Question:
-- Who are the top revenue-generating customers?
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


------------------------------------------------------------
-- 8. DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES
------------------------------------------------------------
-- Business Question:
-- Which countries contribute the most to item sales?
-- Note:
-- Customers are high cardinality, countries are low cardinality
SELECT 
    c.country,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;
